services:
  db:
    image: ankane/pgvector:latest
    container_name: postgres_db
    restart: always
    # 不仅仅读取 env_file，还要手动建立映射关系
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: